{% set name = "jhub-client" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jhub-client-{{ version }}.tar.gz
  sha256: 1d84630c69b893a4d3afa9ae0010315a73ad17fa94af498e672308894aa3be50

build:
  number: 0
  noarch: python
  entry_points:
    - jhubctl=jhub_client.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - aiohttp
    - yarl

test:
  imports:
    - jhub_client
  commands:
    - pip check
    - jhubctl --help
  requires:
    - pip

about:
  home: https://github.com/Quansight/jhub-client
  summary: Library and Client for managing, benchmarking, and interacting with jupyterhub
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
