{% set name = "jhub-client" %}
{% set version = "0.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jhub-client-{{ version }}.tar.gz
  sha256: 758ead99978403fa2379599df124a34c8e46bfe74a7d3dffa9c67ee40af6c6e4

build:
  number: 1
  noarch: python
  entry_points:
    - jhubctl=jhub_client.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - yarl

test:
  imports:
    - jhub_client
  commands:
    - pip check
    - jhubctl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Quansight/jhub-client
  summary: Library and Client for managing, benchmarking, and interacting with jupyterhub
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
