{% set name = "jhub-client" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jhub-client-{{ version }}.tar.gz
  sha256: c133240bcc1503943ad7c4ba6f591ed5b5814c722acf5629cf54d4e034e0ca7b

build:
  number: 0
  noarch: python
  entry_points:
    - jhubctl=jhub_client.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aiohttp
    - yarl

test:
  imports:
    - jhub_client
  commands:
    - pip check
    - jhubctl --help
  requires:
    - pip

about:
  home: https://github.com/Quansight/jhub-client
  summary: Library and Client for managing, benchmarking, and interacting with jupyterhub
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
